{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "intern-chart-3.serviceAccountName" . }}
  labels:
{{ include "intern-chart-3.labels" . | indent 4 }}
{{- end -}}
